### ISSUE TITLE
Linked data canonicalization hash

### ISSUE THREAD

**Issue by clehner** [w3c-ccg/ethereum-eip712-signature-2021-spec#10]
To support linked data canonicalization, define a property to contain a digest of the input document and proof options, as would be done with [ld-proofs](https://w3c-ccg.github.io/ld-proofs/#create-verify-hash-algorithm), e.g. converting the input from JSON-LD to RDF, applying URDNA2015, serializing the result as NQuads and hashing it with SHA256. This property should be added to the proof object immediately before signing. A verifier can verify it to ensure that JSON-LD terms in the document expand to the expected values. This would allow the signing input to remain as a "friendly-looking" object, while ensuring that information in JSON-LD contexts is included in the signing input.

**Comment by awoie** [comment]
On 14 October we discussed we discussed this and the resolution is we want to introduce non-normative language for people who want to include a hash of the semantic context. 

Expecting some PR that introduces some non-normative language for this.

**Comment by awoie** [comment]
@bumblefudge ^^
