### ISSUE TITLE
Update OWNERS and LICENSE.md as per CCG work item guidelines

### ISSUE THREAD

**Issue by wyc** [w3c-ccg/ethereum-eip712-signature-2021-spec#16]
Please see the instructions here: https://w3c-ccg.github.io/create_work_item.html

**Comment by clehner** [comment]
Updating the files in #18.

@wyc could you, or someone else with access, update the access settings and repo topic?

> - Update collaborators (through github interface)
>   - Settings > Manage Access
>     - Chairs: Admin
>     - Editors: Write
>     - Contributors: View
>   - Give the CODEOWNERS “maintain” access
> - Add repo topic: (through github interface)
>   - workitem OR registry
>   - w3c-ccg

**Comment by wyc** [comment]
Fixed! Thanks
