### ISSUE TITLE
Remove JCS or replace with EIP712/RDF canonicalization

### ISSUE THREAD

**Issue by awoie** [w3c-ccg/ethereum-eip712-signature-2021-spec#17]
Currently, JCS is specified as the canonicalisation algorithm but in fact is not required since the EIP712 scheme implicitly canonicalises the data to be signed.

**Comment by bumblefudge** [comment]
on call today, we discussed retaining JCS only for deterministically generated schemata; Joel will write up some language for the auto-generated schema section and test vectors.

**Comment by awoie** [comment]
@bumblefudge to provide an update on the next meeting.
