### ISSUE TITLE
Consider names for eip712Domain and children

### ISSUE THREAD

**Issue by OR13** [w3c-ccg/ethereum-eip712-signature-2021-spec#5]
You get to define the vocab, so you can be more compact in the proof field names, and uses JSON-LD to handle the __context__ (information, definitions, usage, etc.... and of courses the file).

```
"eip712Domain": {
        "messageSchema": "https://example.com/schemas/v1",
        "primaryType": "VerifiableCredential"
}
```

```
"eip712": {
        "schema": "https://example.com/schemas/v1",
        "type": "VerifiableCredential"
}
```

**Comment by awoie** [comment]
As per WG call on Nov 11th, closing this issue since #32 addressed the naming issue.
